language: node_js
node_js:
- node

deploy:
  provider: heroku
  api_key:
    secure: SCBKyl23OapqtqtuOvkWAUgaBmRt0bVqNLjnVtHKdVGBHkMsMOu1UEFEixsZ7L9vYjdgFzAxLlFQU0ifdrmQHpGW3hfN7VSqSW/+HIXgCMN5EQALcTMAqvYSaXBgxCOHW12TgaUUZc1fC2dGxX9e55N5AxzfBD9F0L7TR+88G5C1OmDbHlILQNGYvTlfyqJnMICE8sEVS2/8nT3oCI8DiLqOQb6P5hI08g1t2RB6qKn/7UwENa3+kONFe4IZZN7A6dL7kQ20qTWyGEdqaAGVJdVwEeqBiF12LeR7JA0mKTdK62YMlmJP6xzQGGWkqG/PLYj773+4SiRRj2PR61ptyQuWMpykkWQcEbeOS84Zao61ho9YoEsIIJnGn5dVgJsIUsRC1T3jiiY+sYowMh41+2JCtb9ymy7NepXMAy3LdbU3OrBT/v2HwIUQggqVl9iqoo6zC1UDIRpg/HWVt1+ajKldkPbAvFg8eC3FMBMDdjxWKkrXlYCoMCxqh55tNLgNhFbvyjGdjRaF+usJKQcD0KUzmFJ4wyFwQmnzk6GEh7fWikkZeiTDLnbNQ7oXwyTYUsdcQT/8NzUuMQT1uu2hsQaJkVb1fl+ZESioM8YAz1+S2ArLT/3DAOKolg/+zjMk5i6eNSVrcJvC2yo0jTaPQc7Qz/4GWmzlllVpI0YGhrU=
  app: synonymous